[package]
name = "gpredomicsR"
version = "0.1.0"
edition = "2021"

[dependencies]
extendr-api = "0.3"
extendr-macros = "0.3"
#gpredomics = { git = "https://github.com/predomics/gpredomics.git" }
gpredomics = { path = "../gpredomicsh" }

[lib]
crate-type = ["cdylib"]