general:
  seed: 42
  algo: ga
  thread_number: 4
  log_level: debug
  language: ter,bin
  data_type: log,raw
  data_type_minimum: 1e-5 # this is only usefull for data_type prevalence (where it is a threshold) or log (where it replaces values below)
  fit: specificity
  k_penalty: 0.01
  overfit_penalty: 0.0 # setting this will trigger the removal of a random fold in the train population (change fold_number in CV to ajust)
  fpr_penalty: 1.0
  fnr_penalty: 0.5

cv:
  fold_number: 10

data:
  X: "Xtrain.tsv"
  y: "Ytrain.tsv"
  Xtest: "Xtest.tsv"
  ytest: "Ytest.tsv"
  pvalue_method: wilcoxon
  feature_minimal_prevalence_pct: 10 # per class, e.g. if any of the class reaches this level
  feature_maximal_pvalue: 0.01 # feature with differences less significant than this will be removed
  feature_minimal_feature_value: 0.0001

ga:
  population_size: 1000
  max_epochs: 500
  min_epochs: 100
  max_age_best_model: 20
  kmin: 1
  kmax: 50 # do we keep it? 
  select_elite_pct: 10
  select_random_pct: 30
  mutated_children_pct: 80
  mutated_features_pct: 10
  mutation_non_null_chance_pct: 20
  feature_importance_permutations: 100
  keep_all_generation: false