# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gpredomicsR_wrappers", use_symbols = TRUE, package_name = "gpredomicsR")

#' @usage NULL
#' @useDynLib gpredomicsR, .registration = TRUE
NULL

#' The simple genetic algorithm (ga) produce a Population from a Param object
#' the RunningFlag object is convenient when launching ga in a subthread, it must be
#' provided (but you can let it live its own way)
#' @export
ga <- function(param, running_flag) .Call(wrap__ga, param, running_flag)

#' @export 
RunningFlag <- new.env(parent = emptyenv())

RunningFlag$new <- function() .Call(wrap__RunningFlag__new)

RunningFlag$stop <- function() invisible(.Call(wrap__RunningFlag__stop, self))

RunningFlag$is_running <- function() .Call(wrap__RunningFlag__is_running, self)

RunningFlag$reset <- function() invisible(.Call(wrap__RunningFlag__reset, self))

#' @rdname RunningFlag
#' @usage NULL
#' @export
`$.RunningFlag` <- function (self, name) { func <- RunningFlag[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RunningFlag` <- `$.RunningFlag`

#' @export
Experiment <- new.env(parent = emptyenv())

Experiment$individual <- function(generation, order) .Call(wrap__Experiment__individual, self, generation, order)

Experiment$test_data <- function() .Call(wrap__Experiment__test_data, self)

Experiment$train_data <- function() .Call(wrap__Experiment__train_data, self)

Experiment$get_data_robj <- function(train) .Call(wrap__Experiment__get_data_robj, self, train)

Experiment$get_data <- function(train) .Call(wrap__Experiment__get_data, self, train)

Experiment$get_generation <- function(generation) .Call(wrap__Experiment__get_generation, self, generation)

Experiment$generation_number <- function() .Call(wrap__Experiment__generation_number, self)

Experiment$population_size <- function(generation) .Call(wrap__Experiment__population_size, self, generation)

#' @rdname Experiment
#' @usage NULL
#' @export
`$.Experiment` <- function (self, name) { func <- Experiment[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Experiment` <- `$.Experiment`

#' @export 
Param <- new.env(parent = emptyenv())

Param$new <- function() .Call(wrap__Param__new)

Param$load <- function(file_path) .Call(wrap__Param__load, file_path)

Param$get <- function() .Call(wrap__Param__get, self)

Param$set <- function(variable, value) invisible(.Call(wrap__Param__set, self, variable, value))

Param$set_string <- function(variable, string) invisible(.Call(wrap__Param__set_string, self, variable, string))

#' @rdname Param
#' @usage NULL
#' @export
`$.Param` <- function (self, name) { func <- Param[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Param` <- `$.Param`

#' @export
GLogger <- new.env(parent = emptyenv())

GLogger$new <- function() .Call(wrap__GLogger__new)

GLogger$level <- function(level) .Call(wrap__GLogger__level, level)

GLogger$get <- function(param) .Call(wrap__GLogger__get, param)

GLogger$set_level <- function(level) invisible(.Call(wrap__GLogger__set_level, self, level))

#' @rdname GLogger
#' @usage NULL
#' @export
`$.GLogger` <- function (self, name) { func <- GLogger[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GLogger` <- `$.GLogger`

#' @export
Individual <- new.env(parent = emptyenv())

Individual$new <- function() .Call(wrap__Individual__new)

Individual$get <- function() .Call(wrap__Individual__get, self)

Individual$compute_auc <- function(data, min_value) invisible(.Call(wrap__Individual__compute_auc, self, data, min_value))

Individual$compute_metrics <- function(data, min_value) invisible(.Call(wrap__Individual__compute_metrics, self, data, min_value))

Individual$evaluate <- function(data, min_value) .Call(wrap__Individual__evaluate, self, data, min_value)

Individual$to_string <- function() .Call(wrap__Individual__to_string, self)

#' @rdname Individual
#' @usage NULL
#' @export
`$.Individual` <- function (self, name) { func <- Individual[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Individual` <- `$.Individual`


# nolint end
